<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Meziantou.Framework.FullPath" Version="1.1.21" />
    <PackageReference Include="Meziantou.Framework.TemporaryDirectory" Version="1.0.40" />
    <PackageReference Include="Meziantou.ProjectConfiguration" Version="1.0.20" />
    <PackageReference Include="XUnitToFluentAssertionsAnalyzer" Version="1.0.0" />
  </ItemGroup>
</Project>