<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Meziantou.Framework.FullPath" Version="2.1.6" />
    <PackageReference Include="Meziantou.Framework.TemporaryDirectory" Version="2.0.7" />
    <PackageReference Include="Meziantou.ProjectConfiguration" Version="1.0.0" />
    <PackageReference Include="XUnitToFluentAssertionsAnalyzer" Version="1.0.0" />
  </ItemGroup>
</Project>